import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <button className="btn">neutral</button>
            <button className="btn btn-primary">primary</button>
            <button className="btn btn-secondary rounded-full">secondary</button>
            <button className="btn btn-accent">accent</button>
            <button className="btn btn-ghost">ghost</button>
            <button className="btn btn-link">link</button>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}

export default Home
