import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import RecentExperience from '../src/components/catagory/RecentExperience'
import Search from '../src/components/catagory/Search'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Extension Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;500;600;700&display=swap" rel="stylesheet"></link>

      </Head>

      <main >

        <RecentExperience />

      </main>


    </div>
  )
}

export default Home
